# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Expose ports to the host.
  config.vm.network "forwarded_port", guest: 4646, host: 4646, host_ip: "127.0.0.1"    # Nomad
  config.vm.network "forwarded_port", guest: 8500, host: 8500, host_ip: "127.0.0.1"    # Consul UI
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"    # Nomad Autoscaler health check
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"    # Demo webapp
  config.vm.network "forwarded_port", guest: 1936, host: 1936, host_ip: "127.0.0.1"    # HAProxy stats
  config.vm.network "forwarded_port", guest: 9090, host: 9090, host_ip: "127.0.0.1"    # Prometheus
  config.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"    # Grafana
  config.vm.network "forwarded_port", guest: 9002, host: 9002, host_ip: "127.0.0.1"    # Dashboard

  # config.vm.hostname = "pack"
  config.vm.define "pack" do |pack|
    pack.vm.hostname = "pack"
  end

  # Share current directory with jobs and configuration files with the VM. Add
  # the shared files in a sub-dir.
  config.vm.synced_folder "./", "/home/vagrant/nomad-autoscaler"
  config.vm.synced_folder "../shared", "/home/vagrant/nomad-autoscaler-shared"

  # VM configuration.
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "file", File::NULL ] # https://bugs.launchpad.net/cloud-images/+bug/1874453
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Provision demo dependencies.
  #   - Downloads and install Nomad, Consul and Docker
  # Only runs when the VM is created.
  config.vm.provision "deps", type: "shell", inline: <<-SHELL

    mkdir /tmp/downloads

    # Install dependencies.
    apt-get update
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      jq \
      software-properties-common \
      zip \
      net-tools

    nomad_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/nomad | jq -r '.current_version')
    consul_version=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/consul | jq -r '.current_version')
    nomad_pack_version="0.0.1-techpreview2"

    # Download and install Docker.
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
    apt-get update
    apt-get install -y \
      docker-ce \
      docker-ce-cli \
      containerd.io
    docker run hello-world
    usermod -aG docker vagrant

    # Install Hey.
    apt-get install -y hey

    # Download and install Nomad and Consul.
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all \
      https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip \
      https://releases.hashicorp.com/consul/${consul_version}/consul_${consul_version}_linux_amd64.zip \
      https://releases.hashicorp.com/nomad-pack/${nomad_pack_version}/nomad-pack_${nomad_pack_version}_linux_amd64.zip
    unzip nomad_${nomad_version}_linux_amd64.zip
    unzip consul_${consul_version}_linux_amd64.zip
    unzip nomad-pack_${nomad_pack_version}_linux_amd64.zip
    mkdir -p /opt/hashicorp/bin
    mv nomad consul nomad-pack /opt/hashicorp/bin
    chmod +x /opt/hashicorp/bin/{nomad,consul,nomad-pack}
    ln -s /opt/hashicorp/bin/{nomad,consul,nomad-pack} /usr/local/bin
    popd

    # Download and install CNI Plugin
    echo "Starting CIN Plugin Install"
    pushd /tmp/downloads
    curl --silent --show-error --remote-name-all -L -o cni-plugins.tgz "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.0.0.tgz
    sudo mkdir -p /opt/cni/bin
    sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz
    popd

    # Configure to allow container traffic through the bridge network via iptables
    echo "Configuring iptable bridge"
    echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-arptables
    echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-ip6tables
    echo 1 | sudo tee /proc/sys/net/bridge/bridge-nf-call-iptables

    rm -fr /tmp/downloads
  SHELL

  # Setup demo dependencies.
  #   - Create daemons for Nomad and Consul
  # Runs everytime the VM starts.
  config.vm.provision "app:setup", type: "shell", run: "always", inline: <<-SHELL
    # Create paths for Nomad host volumes.
    mkdir -p /opt/nomad-volumes
    pushd /opt/nomad-volumes
    mkdir -p grafana
    chown 472:472 grafana
    popd

    # Configure the Nomad and Consul daemons.
    pushd /home/vagrant/nomad-autoscaler-shared
    for t in consul nomad; do
      cp ${t}.service /etc/systemd/system/
      mkdir -p /etc/${t}.d
    done
    popd

    # Copy across the config files.
    cp /home/vagrant/nomad-autoscaler-shared/consul.hcl /etc/consul.d/
    cp /home/vagrant/nomad-autoscaler/files/nomad.hcl /etc/nomad.d/
    sudo cp /home/vagrant/nomad-autoscaler/files/10-net-bridge.conf /etc/sysctl.d/

    # Enable and start the daemons
    systemctl enable consul
    systemctl restart consul
    sudo systemctl enable nomad
    sudo systemctl restart nomad
  SHELL

end
